//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UzaktanEgitimDiziFilmBlogSitesi
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLMESAJLAR
    {
        public int İd { get; set; }
        public string Email { get; set; }
        public string TEL { get; set; }
        public string Sehır { get; set; }
        public string Mesaj { get; set; }
        public string ISIM { get; set; }
    }
}
